(* Automatically generated by bin/wrappergen
 * Do not edit this file directly! *)

signature C0VM_NATIVE = 
sig
   val native_index : string -> int
end

structure C0VMNative :> C0VM_NATIVE = 
struct

fun native_index("") =                      ~1

(* args *)
  | native_index("args_flag") =             0
  | native_index("args_int") =              1
  | native_index("args_parse") =            2
  | native_index("args_string") =           3

(* clock *)
  | native_index("millisecs") =             4
  | native_index("now") =                   5

(* conio *)
  | native_index("error") =                 6
  | native_index("print") =                 7
  | native_index("printbool") =             8
  | native_index("printchar") =             9
  | native_index("printint") =              10
  | native_index("println") =               11
  | native_index("readline") =              12

(* curses *)
  | native_index("c_addch") =               13
  | native_index("c_cbreak") =              14
  | native_index("c_curs_set") =            15
  | native_index("c_delch") =               16
  | native_index("c_endwin") =              17
  | native_index("c_erase") =               18
  | native_index("c_getch") =               19
  | native_index("c_initscr") =             20
  | native_index("c_keypad") =              21
  | native_index("c_move") =                22
  | native_index("c_noecho") =              23
  | native_index("c_refresh") =             24
  | native_index("c_subwin") =              25
  | native_index("c_waddch") =              26
  | native_index("c_waddstr") =             27
  | native_index("c_wclear") =              28
  | native_index("c_werase") =              29
  | native_index("c_wmove") =               30
  | native_index("c_wrefresh") =            31
  | native_index("c_wstandend") =           32
  | native_index("c_wstandout") =           33
  | native_index("cc_getbegx") =            34
  | native_index("cc_getbegy") =            35
  | native_index("cc_getmaxx") =            36
  | native_index("cc_getmaxy") =            37
  | native_index("cc_getx") =               38
  | native_index("cc_gety") =               39
  | native_index("cc_highlight") =          40
  | native_index("cc_key_is_backspace") =   41
  | native_index("cc_key_is_down") =        42
  | native_index("cc_key_is_enter") =       43
  | native_index("cc_key_is_left") =        44
  | native_index("cc_key_is_right") =       45
  | native_index("cc_key_is_up") =          46
  | native_index("cc_wboldoff") =           47
  | native_index("cc_wboldon") =            48
  | native_index("cc_wdimoff") =            49
  | native_index("cc_wdimon") =             50
  | native_index("cc_wreverseoff") =        51
  | native_index("cc_wreverseon") =         52
  | native_index("cc_wunderoff") =          53
  | native_index("cc_wunderon") =           54

(* file *)
  | native_index("file_close") =            55
  | native_index("file_eof") =              56
  | native_index("file_read") =             57
  | native_index("file_readline") =         58

(* img *)
  | native_index("image_clone") =           59
  | native_index("image_create") =          60
  | native_index("image_data") =            61
  | native_index("image_destroy") =         62
  | native_index("image_height") =          63
  | native_index("image_load") =            64
  | native_index("image_save") =            65
  | native_index("image_subimage") =        66
  | native_index("image_width") =           67

(* parse *)
  | native_index("parse_bool") =            68
  | native_index("parse_int") =             69

(* string *)
  | native_index("char_chr") =              70
  | native_index("char_ord") =              71
  | native_index("string_charat") =         72
  | native_index("string_compare") =        73
  | native_index("string_equal") =          74
  | native_index("string_from_chararray") = 75
  | native_index("string_frombool") =       76
  | native_index("string_fromchar") =       77
  | native_index("string_fromint") =        78
  | native_index("string_join") =           79
  | native_index("string_length") =         80
  | native_index("string_sub") =            81
  | native_index("string_terminated") =     82
  | native_index("string_to_chararray") =   83
  | native_index("string_tolower") =        84

(* unknown *)
  | native_index(s) =                       ~1

end
