(* Automatically generated by bin/wrappergen
 * Do not edit this file directly! *)

signature C0VM_NATIVE = 
sig
   val native_index : string -> int
end

structure C0VMNative :> C0VM_NATIVE = 
struct

fun native_index("") =                      ~1

(* args *)
  | native_index("args_flag") =             0
  | native_index("args_int") =              1
  | native_index("args_parse") =            2
  | native_index("args_string") =           3

(* conio *)
  | native_index("error") =                 4
  | native_index("print") =                 5
  | native_index("printbool") =             6
  | native_index("printchar") =             7
  | native_index("printint") =              8
  | native_index("println") =               9
  | native_index("readline") =              10

(* curses *)
  | native_index("c_addch") =               11
  | native_index("c_cbreak") =              12
  | native_index("c_curs_set") =            13
  | native_index("c_delch") =               14
  | native_index("c_endwin") =              15
  | native_index("c_erase") =               16
  | native_index("c_getch") =               17
  | native_index("c_initscr") =             18
  | native_index("c_keypad") =              19
  | native_index("c_move") =                20
  | native_index("c_noecho") =              21
  | native_index("c_refresh") =             22
  | native_index("c_subwin") =              23
  | native_index("c_waddch") =              24
  | native_index("c_waddstr") =             25
  | native_index("c_wclear") =              26
  | native_index("c_werase") =              27
  | native_index("c_wmove") =               28
  | native_index("c_wrefresh") =            29
  | native_index("c_wstandend") =           30
  | native_index("c_wstandout") =           31
  | native_index("cc_getbegx") =            32
  | native_index("cc_getbegy") =            33
  | native_index("cc_getmaxx") =            34
  | native_index("cc_getmaxy") =            35
  | native_index("cc_getx") =               36
  | native_index("cc_gety") =               37
  | native_index("cc_highlight") =          38
  | native_index("cc_key_is_backspace") =   39
  | native_index("cc_key_is_down") =        40
  | native_index("cc_key_is_enter") =       41
  | native_index("cc_key_is_left") =        42
  | native_index("cc_key_is_right") =       43
  | native_index("cc_key_is_up") =          44
  | native_index("cc_wboldoff") =           45
  | native_index("cc_wboldon") =            46
  | native_index("cc_wdimoff") =            47
  | native_index("cc_wdimon") =             48
  | native_index("cc_wreverseoff") =        49
  | native_index("cc_wreverseon") =         50
  | native_index("cc_wunderoff") =          51
  | native_index("cc_wunderon") =           52

(* file *)
  | native_index("file_close") =            53
  | native_index("file_eof") =              54
  | native_index("file_read") =             55
  | native_index("file_readline") =         56

(* img *)
  | native_index("image_clone") =           57
  | native_index("image_create") =          58
  | native_index("image_data") =            59
  | native_index("image_destroy") =         60
  | native_index("image_height") =          61
  | native_index("image_load") =            62
  | native_index("image_save") =            63
  | native_index("image_subimage") =        64
  | native_index("image_width") =           65

(* parse *)
  | native_index("parse_bool") =            66
  | native_index("parse_int") =             67

(* string *)
  | native_index("char_chr") =              68
  | native_index("char_ord") =              69
  | native_index("string_charat") =         70
  | native_index("string_compare") =        71
  | native_index("string_equal") =          72
  | native_index("string_from_chararray") = 73
  | native_index("string_frombool") =       74
  | native_index("string_fromchar") =       75
  | native_index("string_fromint") =        76
  | native_index("string_join") =           77
  | native_index("string_length") =         78
  | native_index("string_sub") =            79
  | native_index("string_terminated") =     80
  | native_index("string_to_chararray") =   81
  | native_index("string_tolower") =        82

(* unknown *)
  | native_index(s) =                       ~1

end
