/* 15411_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen 15411' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/15411', which in turn was likely
 * invoked by 'make libs'. */

#include <inttypes.h>
#include <c0runtime.h>

/* Headers */

typedef int fpt;
fpt fadd(fpt x, fpt y);
fpt fsub(fpt x, fpt y);
fpt fmul(fpt x, fpt y);
fpt fdiv(fpt x, fpt y);
bool fless(fpt x, fpt y);
fpt itof(int n);
int ftoi(fpt x);
void print_fpt(fpt x);
void print_int(int n);
void print_hex(int n);

/* Wrappers */

void *__c0ffi_fadd(void **args) {
  return (void *) fadd((fpt) args[0], (fpt) args[1]);
}

void *__c0ffi_fsub(void **args) {
  return (void *) fsub((fpt) args[0], (fpt) args[1]);
}

void *__c0ffi_fmul(void **args) {
  return (void *) fmul((fpt) args[0], (fpt) args[1]);
}

void *__c0ffi_fdiv(void **args) {
  return (void *) fdiv((fpt) args[0], (fpt) args[1]);
}

void *__c0ffi_fless(void **args) {
  return (void *) (intptr_t) fless((fpt) args[0], (fpt) args[1]);
}

void *__c0ffi_itof(void **args) {
  return (void *) itof((int) (intptr_t) args[0]);
}

void *__c0ffi_ftoi(void **args) {
  return (void *) (intptr_t) ftoi((fpt) args[0]);
}

void *__c0ffi_print_fpt(void **args) {
  print_fpt((fpt) args[0]);
  return NULL;
}

void *__c0ffi_print_int(void **args) {
  print_int((int) (intptr_t) args[0]);
  return NULL;
}

void *__c0ffi_print_hex(void **args) {
  print_hex((int) (intptr_t) args[0]);
  return NULL;
}

