
"enable filetype for command below
filetype on

"use c indentation style and syntax highlighting for c, c++, and c0 files
autocmd FileType c,cpp :set cindent
autocmd FileType c,cpp :setf c
autocmd FileType c,cpp :set expandtab
au BufEnter *.c0 setf c
au BufEnter *.c0 set cindent 
au BufEnter *.c0 set expandtab
au BufEnter *.c0 set rules
au BufEnter *.c0 syntax on
" show line numbers
"au BufEnter *.c0 set number
