/* curses_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen curses' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/curses', which in turn was likely
 * invoked by 'make libs'. */

#include <inttypes.h>
#include <c0runtime.h>

/* Headers */

struct _win_st;
typedef struct _win_st WINDOW;
WINDOW * c_initscr();
void c_cbreak();
void c_noecho();
void c_keypad(WINDOW * w, bool b);
int c_getch();
void c_addch(int c);
void c_waddch(WINDOW * w, int c);
void c_waddstr(WINDOW * w, c0_string s);
void c_wstandout(WINDOW * w);
void c_wstandend(WINDOW * w);
void c_delch();
void c_erase();
void c_werase(WINDOW * w);
void c_wclear(WINDOW * w);
void c_move(int y, int x);
void c_wmove(WINDOW * w, int y, int x);
void c_refresh();
void c_wrefresh(WINDOW * w);
int c_endwin();
int c_curs_set(int visibility);
WINDOW * c_subwin(WINDOW * orig, int nlines, int ncols, int begin_y, int begin_x);
void cc_wboldon(WINDOW * w);
void cc_wboldoff(WINDOW * w);
void cc_wdimon(WINDOW * w);
void cc_wdimoff(WINDOW * w);
void cc_wreverseon(WINDOW * w);
void cc_wreverseoff(WINDOW * w);
void cc_wunderon(WINDOW * w);
void cc_wunderoff(WINDOW * w);
int cc_highlight(int c);
int cc_getx(WINDOW * w);
int cc_gety(WINDOW * w);
int cc_getmaxx(WINDOW * w);
int cc_getmaxy(WINDOW * w);
int cc_getbegx(WINDOW * w);
int cc_getbegy(WINDOW * w);
bool cc_key_is_enter(int key);
bool cc_key_is_backspace(int key);
bool cc_key_is_left(int key);
bool cc_key_is_right(int key);
bool cc_key_is_up(int key);
bool cc_key_is_down(int key);

/* Wrappers */

void *__c0ffi_c_initscr(void **args) {
  (void) args; /* suppress error */
  return (void *) c_initscr();
}

void *__c0ffi_c_cbreak(void **args) {
  (void) args; /* suppress error */
  c_cbreak();
  return NULL;
}

void *__c0ffi_c_noecho(void **args) {
  (void) args; /* suppress error */
  c_noecho();
  return NULL;
}

void *__c0ffi_c_keypad(void **args) {
  c_keypad((WINDOW *) args[0], (bool) (intptr_t) args[1]);
  return NULL;
}

void *__c0ffi_c_getch(void **args) {
  (void) args; /* suppress error */
  return (void *) (intptr_t) c_getch();
}

void *__c0ffi_c_addch(void **args) {
  c_addch((int) (intptr_t) args[0]);
  return NULL;
}

void *__c0ffi_c_waddch(void **args) {
  c_waddch((WINDOW *) args[0], (int) (intptr_t) args[1]);
  return NULL;
}

void *__c0ffi_c_waddstr(void **args) {
  c_waddstr((WINDOW *) args[0], (c0_string) args[1]);
  return NULL;
}

void *__c0ffi_c_wstandout(void **args) {
  c_wstandout((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_c_wstandend(void **args) {
  c_wstandend((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_c_delch(void **args) {
  (void) args; /* suppress error */
  c_delch();
  return NULL;
}

void *__c0ffi_c_erase(void **args) {
  (void) args; /* suppress error */
  c_erase();
  return NULL;
}

void *__c0ffi_c_werase(void **args) {
  c_werase((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_c_wclear(void **args) {
  c_wclear((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_c_move(void **args) {
  c_move((int) (intptr_t) args[0], (int) (intptr_t) args[1]);
  return NULL;
}

void *__c0ffi_c_wmove(void **args) {
  c_wmove((WINDOW *) args[0], (int) (intptr_t) args[1], (int) (intptr_t) args[2]);
  return NULL;
}

void *__c0ffi_c_refresh(void **args) {
  (void) args; /* suppress error */
  c_refresh();
  return NULL;
}

void *__c0ffi_c_wrefresh(void **args) {
  c_wrefresh((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_c_endwin(void **args) {
  (void) args; /* suppress error */
  return (void *) (intptr_t) c_endwin();
}

void *__c0ffi_c_curs_set(void **args) {
  return (void *) (intptr_t) c_curs_set((int) (intptr_t) args[0]);
}

void *__c0ffi_c_subwin(void **args) {
  return (void *) c_subwin((WINDOW *) args[0], (int) (intptr_t) args[1], (int) (intptr_t) args[2], (int) (intptr_t) args[3], (int) (intptr_t) args[4]);
}

void *__c0ffi_cc_wboldon(void **args) {
  cc_wboldon((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wboldoff(void **args) {
  cc_wboldoff((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wdimon(void **args) {
  cc_wdimon((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wdimoff(void **args) {
  cc_wdimoff((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wreverseon(void **args) {
  cc_wreverseon((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wreverseoff(void **args) {
  cc_wreverseoff((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wunderon(void **args) {
  cc_wunderon((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_wunderoff(void **args) {
  cc_wunderoff((WINDOW *) args[0]);
  return NULL;
}

void *__c0ffi_cc_highlight(void **args) {
  return (void *) (intptr_t) cc_highlight((int) (intptr_t) args[0]);
}

void *__c0ffi_cc_getx(void **args) {
  return (void *) (intptr_t) cc_getx((WINDOW *) args[0]);
}

void *__c0ffi_cc_gety(void **args) {
  return (void *) (intptr_t) cc_gety((WINDOW *) args[0]);
}

void *__c0ffi_cc_getmaxx(void **args) {
  return (void *) (intptr_t) cc_getmaxx((WINDOW *) args[0]);
}

void *__c0ffi_cc_getmaxy(void **args) {
  return (void *) (intptr_t) cc_getmaxy((WINDOW *) args[0]);
}

void *__c0ffi_cc_getbegx(void **args) {
  return (void *) (intptr_t) cc_getbegx((WINDOW *) args[0]);
}

void *__c0ffi_cc_getbegy(void **args) {
  return (void *) (intptr_t) cc_getbegy((WINDOW *) args[0]);
}

void *__c0ffi_cc_key_is_enter(void **args) {
  return (void *) (intptr_t) cc_key_is_enter((int) (intptr_t) args[0]);
}

void *__c0ffi_cc_key_is_backspace(void **args) {
  return (void *) (intptr_t) cc_key_is_backspace((int) (intptr_t) args[0]);
}

void *__c0ffi_cc_key_is_left(void **args) {
  return (void *) (intptr_t) cc_key_is_left((int) (intptr_t) args[0]);
}

void *__c0ffi_cc_key_is_right(void **args) {
  return (void *) (intptr_t) cc_key_is_right((int) (intptr_t) args[0]);
}

void *__c0ffi_cc_key_is_up(void **args) {
  return (void *) (intptr_t) cc_key_is_up((int) (intptr_t) args[0]);
}

void *__c0ffi_cc_key_is_down(void **args) {
  return (void *) (intptr_t) cc_key_is_down((int) (intptr_t) args[0]);
}

