/* args_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen args' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/args', which in turn was likely
 * invoked by 'make libs'. */

#include <inttypes.h>
#include <c0runtime.h>

/* Headers */

void args_flag(c0_string name, bool * ptr);
void args_int(c0_string name, int * ptr);
void args_string(c0_string name, c0_string * ptr);
struct args{
  int argc;
  c0_array * argv;
};
struct args * args_parse();

/* Wrappers */

c0_value __c0ffi_args_flag(c0_value *args) {
  args_flag((c0_string)val2ptr(args[0]), (bool *)val2ptr(args[1]));
  return ptr2val(NULL);
}

c0_value __c0ffi_args_int(c0_value *args) {
  args_int((c0_string)val2ptr(args[0]), (int *)val2ptr(args[1]));
  return ptr2val(NULL);
}

c0_value __c0ffi_args_string(c0_value *args) {
  args_string((c0_string)val2ptr(args[0]), (c0_string *)val2ptr(args[1]));
  return ptr2val(NULL);
}

c0_value __c0ffi_args_parse(c0_value *args) {
  (void) args; /* suppress error */
  return ptr2val((void *)args_parse());
}

