/* conio_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen conio' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/conio', which in turn was likely
 * invoked by 'make libs'. */

#include <inttypes.h>
#include <c0runtime.h>

/* Headers */

void print(c0_string s);
void println(c0_string s);
void printint(int i);
void printbool(bool b);
void printchar(c0_char c);
void flush();
bool eof();
c0_string readline();

/* Wrappers */

c0_value __c0ffi_print(c0_value *args) {
  print((c0_string)val2ptr(args[0]));
  return ptr2val(NULL);
}

c0_value __c0ffi_println(c0_value *args) {
  println((c0_string)val2ptr(args[0]));
  return ptr2val(NULL);
}

c0_value __c0ffi_printint(c0_value *args) {
  printint(val2int(args[0]));
  return ptr2val(NULL);
}

c0_value __c0ffi_printbool(c0_value *args) {
  printbool((bool)val2int(args[0]));
  return ptr2val(NULL);
}

c0_value __c0ffi_printchar(c0_value *args) {
  printchar((c0_char)val2int(args[0]));
  return ptr2val(NULL);
}

c0_value __c0ffi_flush(c0_value *args) {
  (void) args; /* suppress error */
  flush();
  return ptr2val(NULL);
}

c0_value __c0ffi_eof(c0_value *args) {
  (void) args; /* suppress error */
  return int2val((c0_int)eof());
}

c0_value __c0ffi_readline(c0_value *args) {
  (void) args; /* suppress error */
  return ptr2val((void *)readline());
}

