/* img_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen img' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/img', which in turn was likely
 * invoked by 'make libs'. */

#include <inttypes.h>
#include <c0runtime.h>

/* Headers */

struct image;
typedef struct image * image_t;
int image_width(image_t image);
int image_height(image_t image);
image_t image_create(int width, int height);
image_t image_clone(image_t image);
void image_destroy(image_t image);
image_t image_subimage(image_t image, int x, int y, int width, int height);
image_t image_load(c0_string path);
void image_save(image_t image, c0_string path);
c0_array * image_data(image_t image);

/* Wrappers */

void *__c0ffi_image_width(void **args) {
  return (void *) (intptr_t) image_width((image_t) args[0]);
}

void *__c0ffi_image_height(void **args) {
  return (void *) (intptr_t) image_height((image_t) args[0]);
}

void *__c0ffi_image_create(void **args) {
  return (void *) image_create((int) (intptr_t) args[0], (int) (intptr_t) args[1]);
}

void *__c0ffi_image_clone(void **args) {
  return (void *) image_clone((image_t) args[0]);
}

void *__c0ffi_image_destroy(void **args) {
  image_destroy((image_t) args[0]);
  return NULL;
}

void *__c0ffi_image_subimage(void **args) {
  return (void *) image_subimage((image_t) args[0], (int) (intptr_t) args[1], (int) (intptr_t) args[2], (int) (intptr_t) args[3], (int) (intptr_t) args[4]);
}

void *__c0ffi_image_load(void **args) {
  return (void *) image_load((c0_string) args[0]);
}

void *__c0ffi_image_save(void **args) {
  image_save((image_t) args[0], (c0_string) args[1]);
  return NULL;
}

void *__c0ffi_image_data(void **args) {
  return (void *) image_data((image_t) args[0]);
}

