/* dub_c0ffi.c
 * This file automatically generated by the command 
 * 'wrappergen dub' - editing is probably bad.
 * 
 * The call to wrappergen was likely probably by 
 * 'make libs/dub', which in turn was likely
 * invoked by 'make libs'. */

#include <inttypes.h>
#include <c0runtime.h>
#include <stdio.h>

/* Headers */

struct dub * dadd(struct dub * x, struct dub * y);
struct dub * dsub(struct dub * x, struct dub * y);
struct dub * dmul(struct dub * x, struct dub * y);
struct dub * ddiv(struct dub * x, struct dub * y);
bool dless(struct dub * x, struct dub * y);
struct dub * itod(int n);
int dtoi(struct dub * x);
void print_dub(struct dub * x);

/* Wrappers */

c0_value __c0ffi_dadd(c0_value *args) {
   //fprintf(stderr, "Calling dadd\n");
  return ptr2val((void *)dadd((struct dub *)val2ptr(args[0]), (struct dub *)val2ptr(args[1])));
}

c0_value __c0ffi_dsub(c0_value *args) {
   //fprintf(stderr, "Calling dsub\n");
  return ptr2val((void *)dsub((struct dub *)val2ptr(args[0]), (struct dub *)val2ptr(args[1])));
}

c0_value __c0ffi_dmul(c0_value *args) {
   //fprintf(stderr, "Calling dmul\n");
  return ptr2val((void *)dmul((struct dub *)val2ptr(args[0]), (struct dub *)val2ptr(args[1])));
}

c0_value __c0ffi_ddiv(c0_value *args) {
   //fprintf(stderr, "Calling ddiv\n");
  return ptr2val((void *)ddiv((struct dub *)val2ptr(args[0]), (struct dub *)val2ptr(args[1])));
}

c0_value __c0ffi_dless(c0_value *args) {
   //fprintf(stderr, "Calling dless\n");
  return int2val((c0_int)dless((struct dub *)val2ptr(args[0]), (struct dub *)val2ptr(args[1])));
}

c0_value __c0ffi_itod(c0_value *args) {
   //fprintf(stderr, "Calling itod\n");
  return ptr2val((void *)itod(val2int(args[0])));
}

c0_value __c0ffi_dtoi(c0_value *args) {
   //fprintf(stderr, "Calling dtoi\n");
  return int2val(dtoi((struct dub *)val2ptr(args[0])));
}

c0_value __c0ffi_print_dub(c0_value *args) {
   //fprintf(stderr, "Calling print_dub\n");
  print_dub((struct dub *)val2ptr(args[0]));
  return ptr2val(NULL);
}

